language: bash

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.10.0
    - DOCKER_VERSION=17.06.2
    - LATEST_TAG=4-1.13
    - FROM_STABILITY_TAG=""
  matrix:
    - WORDPRESS_VER=4 NGINX_VER=1.13 TAG=4-1.13
    - WORDPRESS_VER=4 NGINX_VER=1.12 TAG=4-1.12

install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi
