language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.2.0
  matrix:
    - WORDPRESS_VER=4 NGINX_VER=1.15 TAGS=4-1.15,1.15,1,4,latest
    - WORDPRESS_VER=4 NGINX_VER=1.14 TAGS=4-1.14,1.14
    - WORDPRESS_VER=4 NGINX_VER=1.13 TAGS=4-1.13,1.13

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
